module.exports = {
  pulsate: 'pulsate 3s ease-in-out infinite',
  blink: 'blink 3s ease-in-out infinite',
  hitLeft: 'hitLeft 0.5s ease-in-out',
  hitRight: 'hitRight 3s ease-in-out infinite',
  shake: 'shake 3s ease-in-out infinite',
  drawer: 'fadeIn 0.5s ease-in-out',
  ball: 'ball 3s ease-in-out infinite',
  pullUp: 'pullUp 3s ease-in-out infinite',
  pullDown: 'pullDown 3s ease-in-out infinite',
  pullLeft: 'pullLeft 3s ease-in-out infinite',
  pullRight: 'pullRight 3s ease-in-out infinite',
  jumpInLeft: 'jumpInLeft 3s ease-in-out infinite',
  jumpInRight: 'jumpInRight 3s ease-in-out infinite',
  jumpOutRight: 'jumpOutRight 3s ease-in-out infinite',
  jumpOutLeft: 'jumpOutLeft 3s ease-in-out infinite',
  rollInLeft: 'rollInLeft 3s ease-in-out infinite',
  rollInRight: 'rollInRight 3s ease-in-out infinite',
  rollInTop: 'rollInTop 3s ease-in-out infinite',
  rollInBottom: 'rollInBottom 3s ease-in-out infinite',
  rollOutLeft: 'rollOutLeft 3s ease-in-out infinite',
  rollOutRight: 'rollOutRight 3s ease-in-out infinite',
  rollOutTop: 'rollOutTop 3s ease-in-out infinite',
  rollOutBottom: 'rollOutBottom 3s ease-in-out infinite',
  popIn: 'popIn 0.5s ease-in-out',
  popInLeft: 'popInLeft 3s ease-in-out infinite',
  popInRight: 'popInRight 3s ease-in-out infinite',
  popInTop: 'popInTop 0.5s ease-in-out',
  popInBottom: 'popInBottom 3s ease-in-out infinite',
  popOut: 'popOut 3s ease-in-out infinite',
  popOutLeft: 'popOutLeft 3s ease-in-out infinite',
  popOutRight: 'popOutRight 3s ease-in-out infinite',
  popOutTop: 'popOutTop 3s ease-in-out infinite',
  popOutBottom: 'popOutBottom 3s ease-in-out infinite',
  flip: 'flip 3s ease-in-out infinite',
  flipInX: 'flipInX 3s ease-in-out infinite',
  flipInY: 'flipInY 3s ease-in-out infinite',
  flipOutX: 'flipOutX 3s ease-in-out infinite',
  flipOutY: 'flipOutY 3s ease-in-out infinite',
  fadeIn: 'fadeIn 1s ease-in-out',
  fadeInRight: 'fadeInRight 3s ease-in-out infinite',
  fadeInLeft: 'fadeInLeft 3s ease-in-out infinite',
  fadeInTop: 'fadeInTop 3s ease-in-out infinite',
  fadeInBottom: 'fadeInBottom 3s ease-in-out infinite',
  fadeOut: 'fadeOut 3s ease-in-out infinite',
  fadeOutLeft: 'fadeOutLeft 3s ease-in-out infinite',
  fadeOutRight: 'fadeOutRight 3s ease-in-out infinite',
  fadeOutTop: 'fadeOutTop 3s ease-in-out infinite',
  fadeOutBottom: 'fadeOutBottom 3s ease-in-out infinite',
  driveInLeft: 'driveInLeft 3s ease-in-out infinite',
  driveInRight: 'driveInRight 3s ease-in-out infinite',
  driveInTop: 'driveInTop 0.5s ease-in-out',
  driveInBottom: 'driveInBottom 3s ease-in-out infinite',
  driveOutLeft: 'driveOutLeft 3s ease-in-out infinite',
  driveOutRight: 'driveOutRight 3s ease-in-out infinite',
  driveOutTop: 'driveOutTop 3s ease-in-out infinite',
  driveOutBottom: 'driveOutBottom 3s ease-in-out infinite',
  spin: 'spin 3s ease-in-out infinite',
  spinIn: 'spinIn 3s ease-in-out infinite',
  spinOut: 'spinOut 3s ease-in-out infinite',
  swoopInLeft: 'swoopInLeft 3s ease-in-out infinite',
  swoopInRight: 'swoopInRight 3s ease-in-out infinite',
  swoopInTop: 'swoopInTop 3s ease-in-out infinite',
  swoopInBottom: 'swoopInBottom 3s ease-in-out infinite',
  swoopOutLeft: 'swoopOutLeft 3s ease-in-out infinite',
  swoopOutRight: 'swoopOutRight 3s ease-in-out infinite',
  swoopOutTop: 'swoopOutTop 3s ease-in-out infinite',
  swoopOutBottom: 'swoopOutBottom 3s ease-in-out infinite',
  fold: 'fold 3s ease-in-out infinite',
  unfold: 'unfold 3s ease-in-out infinite',
};
