module.exports = {
  'hvr-pulse': 'hvr-pulse 3s ease-in-out infinite',
  'hvr-pulse-grow': 'hvr-pulse-grow 3s ease-in-out infinite',
  'hvr-pulse-shrink': 'hvr-pulse-shrink 3s ease-in-out infinite',
  'hvr-push': 'hvr-push 3s ease-in-out infinite',
  'hvr-pop': 'hvr-pop 3s ease-in-out infinite',
  'hvr-bob': 'hvr-bob 3s ease-in-out infinite',
  'hvr-bob-float': 'hvr-bob-float 3s ease-in-out infinite',
  'hvr-hang': 'hvr-hang 3s ease-in-out infinite',
  'hvr-hang-sink': 'hvr-hang-sink 3s ease-in-out infinite',
  'hvr-buzz-out': 'hvr-buzz-out 3s ease-in-out infinite',
  'hvr-back-pulse': 'hvr-back-pulse 3s ease-in-out infinite',
  'hvr-ripple-out': 'hvr-ripple-out 3s ease-in-out infinite',
  'hvr-ripple-in': 'hvr-ripple-in 3s ease-in-out infinite',
  'hvr-icon-down': 'hvr-icon-down 3s ease-in-out infinite',
  'hvr-icon-up': 'hvr-icon-up 3s ease-in-out infinite',
  'hvr-icon-drop': 'hvr-icon-drop 3s ease-in-out infinite',
  'hvr-icon-float-away': 'hvr-icon-float-away 3s ease-in-out infinite',
  'hvr-icon-sink-away': 'hvr-icon-sink-away 3s ease-in-out infinite',
  'hvr-icon-pulse': 'hvr-icon-pulse 1s ease-in-out infinite',
  'hvr-icon-pulse-grow': 'hvr-icon-pulse-grow 3s ease-in-out infinite',
  'hvr-icon-pulse-shrink': 'hvr-icon-pulse-shrink 1.5s ease-in-out',
  'hvr-icon-push': 'hvr-icon-push 0.5s ease-in-out',
  'hvr-icon-pop': 'hvr-icon-pop 0.5s ease-in-out',
  'hvr-icon-bob': 'hvr-icon-bob 3s ease-in-out infinite',
  'hvr-icon-bob-float': 'hvr-icon-bob-float 3s ease-in-out infinite',
  'hvr-icon-hang': 'hvr-icon-hang 3s ease-in-out infinite',
  'hvr-icon-hang-sink': 'hvr-icon-hang-sink 3s ease-in-out infinite',
  'hvr-icon-buzz-out': 'hvr-icon-buzz-out 1s ease-in-out',
};
